### ISSUE TITLE
Failure to start v0.1.0 after upgrade to 2021.8.0

### ISSUE THREAD

**Issue by jdwhite** [neggert/hass-egauge#39]
v0.1.0 installed from HACS. After updating to hass-core 2021.8.0 and restarting I see this in my logs:

`ERROR (MainThread) [homeassistant.setup] Setup failed for egauge: Unable to import component: cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by jdwhite** [comment]
I noticed that the eGauge integration is in the stock integrations list now, so tried that after disabling the HACS eGauge integration. UI gave the error "Config flow could not be loaded" and logs reported the same "unable to import component" error.

**Comment by phidauex** [comment]
It looks like this commit on July 20 to HA core renamed a number of the electrical unit constants in homeassistant.const. 'ELECTRICAL_CURRENT_AMPERE' is now 'ELECTRIC_CURRENT_AMPERE'.

From a quick check, the only other change I see is 'VOLT' is now 'ELECTRIC_POTENTIAL_VOLT'. 

I'm not confident on how to install a custom component from source so I'm not sure how I could test the code, otherwise I'd be happy to submit a pull request.

**Comment by phidauex** [comment]
It may also be necessary for the component to register the sensors for long term statistics so they can be used by the Energy Management addition: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by neggert** [comment]
Hi all. Just ran into this issue myself. I should have a fix for the unit renaming soon. It will probably take a little bit longer to figure out what's needed to integrate with the new energy management features, but it's on my todo list.

**Comment by neggert** [comment]
I just released v0.2.0, which should at least restore basic functionality under 2021.8.0. Please give it a try and let me know how it goes.

**Comment by jdwhite** [comment]
Things appear to be back in order. Thanks for the quick resolution!
